run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - goimports
    #    - golint # enable later
    - govet
    - staticcheck
  disable:
    - structcheck # enable later
    - unused # enable later
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0