language: go

go:
  - 1.14.x
  - tip

before_install:
  - go get -t -v ./...

before_script:
  - go install -mod vendor github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - make lint test

after_success:
  - bash <(curl -s https://codecov.io/bash)